### ISSUE TITLE
Graphical bugs with terrain

### ISSUE THREAD

**Issue by Aspyro** [citiesskylines-csur/CSUR#4]
When i build roads with CSUR and the terrain is not perfectly flat, the road doesn't adapt itself to the terrain. I have to correct it myself making the road higher at some point to get the road above the terrain.
I give you an image for the before/after my correction. This one is not the single case nor the single type of road where it happens.
Before : 
![Img02](https://user-images.githubusercontent.com/37420016/78374938-65356e00-75cc-11ea-8df3-87c8e5b4762c.png)

After :
![Img01](https://user-images.githubusercontent.com/37420016/78374406-18ea2e00-75cc-11ea-80ba-529e6a7b43a4.png)

(To correct the elevation of the road I use Move It)

Edit : More example screenshot
![Img04](https://user-images.githubusercontent.com/37420016/78381752-1987c200-75d6-11ea-92d1-55b905806dc1.png)

**Comment by victoriacity** [comment]
Roads in CSUR were designed to **not clip the terrain** to avoid some terrain glitches in cases such as building a sunken highway. Besides most CSUR roads are not center-aligned, while the game only clips terrain symmetrically from the center of the segment. Therefore, CSUR indeed needs more manual terrain adjustment. This issue would be more suitable for CSUR Toolbox to add a feature of asymmetrical terrain clipping.
