### ISSUE TITLE
Non-base module generation

### ISSUE THREAD

**Issue by pinnaval** [citiesskylines-csur/CSUR#7]
I had succeeded generating base roads with bike and pedestrian lanes.
However I can't seem to be able to generate roads with pedestrian lane only (no bikes).

How can I accomplish that?
I use for example
```
make 2R=1R1R2P 1R1R2P=2R
```

**Comment by victoriacity** [comment]
Roads with pedestrian lane only are designated by a `_compact` suffix, see [instructions](https://github.com/citiesskylines-csur/CSUR/wiki/Make-your-own-CSUR-road-asset). So make.bat is invoked as
`make 2R=1R1R2P_compact`
